In [1]:
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd

In [2]:
import os

In [3]:
os.environ["PATH"] = os.environ["PATH"] + ";C:machine_learning_project01/Graphviz/bin;"

In [4]:
os.environ["PATH"]

'C:\\Users\\User\\anaconda3\\envs\\machine_learning_env01;C:\\Users\\User\\anaconda3\\envs\\machine_learning_env01\\Library\\mingw-w64\\bin;C:\\Users\\User\\anaconda3\\envs\\machine_learning_env01\\Library\\usr\\bin;C:\\Users\\User\\anaconda3\\envs\\machine_learning_env01\\Library\\bin;C:\\Users\\User\\anaconda3\\envs\\machine_learning_env01\\Scripts;C:\\Users\\User\\anaconda3\\envs\\machine_learning_env01\\bin;C:\\Users\\User\\anaconda3\\condabin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.2\\bin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.2\\libnvvp;.;.;C:\\Users\\User\\anaconda3\\Library\\bin;C:\\app\\User\\product\\21c\\dbhomeXE\\bin;C:\\Program Files\\Common Files\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Scripts;C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312;C:\\WINDOWS\\System32\\OpenS

In [5]:
iris = load_iris()

x_train = iris.data[:-30]
y_train = iris.target[:-30]

x_test = iris.data[-30:]
y_test = iris.target[-30:]

In [6]:
print(y_train)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2]


In [7]:
print(y_test)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [8]:
from sklearn.ensemble import RandomForestClassifier

In [9]:
rfc=RandomForestClassifier()

In [10]:
rfc

RandomForestClassifier()

In [11]:
rfc.fit(x_train,y_train)
prediction=rfc.predict(x_test)
print(prediction==y_test)

[ True False  True False  True  True False False  True False  True  True
  True False False  True  True  True False  True  True  True  True  True
  True  True  True  True  True  True]


In [12]:
from sklearn.metrics import classification_report

In [13]:
print("Accuracy is :",accuracy_score(prediction,y_test))

Accuracy is : 0.7333333333333333


In [14]:
from sklearn.model_selection import train_test_split
x=iris.data
y=iris.target
X_train, X_test, Y_train, Y_test = train_test_split(x,y,test_size=0.2)
print(y_test)
print(Y_test)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
[0 0 2 2 0 2 0 0 1 1 2 1 2 2 2 2 2 1 0 1 2 2 0 2 2 2 2 0 1 0]


In [15]:
clf=RandomForestClassifier()
clf.fit(X_train,Y_train)

RandomForestClassifier()

In [17]:
prediction_1=clf.predict(X_test)
print("Accuracy is :",accuracy_score(prediction_1,Y_test))

Accuracy is : 0.9333333333333333
